Resources:
  MyInstance:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2
      ImageId: ami-0c3e7919416671c83
      InstanceType: t2.micro
     